force-app/main/default/objects/TestObject__c/TestObject__c.object-meta.xml
<CustomObject>
    <label>TestObject</label>
    <nameField>
        <label>TestObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestObject__c/fields/IsLastUpdateSuccessful__c.field-meta.xml
<CustomField>
    <fullName>IsLastUpdateSuccessful__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Было ли последнее обновление записи успешным?</description>
    <label>IsLastUpdateSuccessful</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TestObject__c/fields/NumberField__c.field-meta.xml
<CustomField>
    <fullName>NumberField__c</fullName>
    <label>NumberField</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TestObject__c/fields/TextField__c.field-meta.xml
<CustomField>
    <fullName>TextField__c</fullName>
    <label>TextField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestObjectUpdatedEvent__e/TestObjectUpdatedEvent__e.object-meta.xml
<CustomObject>
    <label>TestObjectUpdatedEvent</label>
    <pluralLabel>TestObjectUpdatedEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/TestObjectUpdatedEvent__e/fields/IsSuccessfulUpdate__c.field-meta.xml
<CustomField>
    <fullName>IsSuccessfulUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSuccessfulUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TestObjectUpdatedEvent__e/fields/TestObjectId__c.field-meta.xml
<CustomField>
    <fullName>TestObjectId__c</fullName>
    <description>Поле содержащее Id записи, для которой запущен Event.</description>
    <label>TestObjectId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestObjectUpdateEventTriggerHandler.cls
public with sharing class TestObjectUpdateEventTriggerHandler extends TriggerHandler {

    private final Integer NUMBER_OF_UPDATE_ATTEMPTS = 5;

    protected override void afterInsert(Map<Id, sObject> newMap) {
        try {
            update createTestObjectsForUpdate(newMap.values());
        } catch (Exception ex) {
            retryEvent();
        }
    }

    private List<TestObject__c> createTestObjectsForUpdate(List<TestObjectUpdatedEvent__e> newList) {
        List<TestObject__c> testObjectsForUpdate = new List<TestObject__c>();

        for (TestObjectUpdatedEvent__e testObjectUpdateEvent : newList) {
            testObjectsForUpdate.add(
                    new TestObject__c(
                            Id = testObjectUpdateEvent.TestObjectId__c,
                            IsLastUpdateSuccessful__c = testObjectUpdateEvent.IsSuccessfulUpdate__c,
                            TextField__c = '00000000000000000000000000000000000000000000000000000000000000000000000000000' +
                                    '00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000' +
                                    '00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
                    )
            );
        }

        return testObjectsForUpdate;
    }

    private void retryEvent() {
        if (EventBus.TriggerContext.currentContext().retries < NUMBER_OF_UPDATE_ATTEMPTS) {
            throw new EventBus.RetryableException('Error Message');
        } else {
            System.debug('----- ERROR: Cannot update records');
            insert new TestObject__c(
                    Name = 'Batch_UpdateTestObjects_',
                    TextField__c = 'ERROR: Cannot update records',
                    NumberField__c = EventBus.TriggerContext.currentContext().retries
            );
        }
    }
}