force-app/main/default/objects/TestCMT__mdt/TestCMT__mdt.object-meta.xml
<CustomObject>
    <label>TestCMT</label>
    <pluralLabel>TestCMTs</pluralLabel>
</CustomObject>

force-app/main/default/objects/TestCMT__mdt/fields/TextField__c.field-meta.xml
<CustomField>
    <fullName>TextField__c</fullName>
    <label>TextField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SomeClassForTesting.cls
public with sharing class SomeClassForTesting {
    public static String str { private get; set; }

    //----------------------------------------------------------------------------------------------------------
    //CustomMetadataType testing
    @TestVisible
    private Map<String, TestCMT__mdt> testCmdMap {
        get {
            if (testCmdMap == null) {
                testCmdMap = TestCMT__mdt.getAll();
            }

            return testCmdMap;
        }
        set;
    }

    public String getTextFromCmt(String cmtName) {
        return testCmdMap.get(cmtName).TextField__c;
    }
    //----------------------------------------------------------------------------------------------------------
}